"""Adding user information col

Revision ID: b80c852d5225
Revises: a33ee7a88413
Create Date: 2025-02-26 12:22:37.543168

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b80c852d5225"
down_revision: Union[str, None] = "a33ee7a88413"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("information", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "information")
    # ### end Alembic commands ###
