"""removing name and desc

Revision ID: a33ee7a88413
Revises: 4acda2bbbdef
Create Date: 2025-02-26 09:18:06.365856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33ee7a88413'
down_revision: Union[str, None] = '4acda2bbbdef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'description')
    op.drop_column('chat', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('chat', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
