"""adding relationships and chat message types

Revision ID: 4acda2bbbdef
Revises: 8d732df88c9a
Create Date: 2025-02-26 08:21:58.649817

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4acda2bbbdef"
down_revision: Union[str, None] = "8d732df88c9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column("message", sa.Column("type", sa.String(), nullable=False))
    op.add_column("message", sa.Column("is_user", sa.Boolean(), nullable=False))
    op.add_column("message", sa.Column("buttons", sa.String(), nullable=True))
    op.add_column("message", sa.Column("resources", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "resources")
    op.drop_column("message", "buttons")
    op.drop_column("message", "is_user")
    op.drop_column("message", "type")
    op.drop_column("chat", "is_active")
    # ### end Alembic commands ###
